name: flutter_weather_app
description: "A new Flutter project that fetches weather data using OpenWeatherMap API and manages state with BLoC."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: "^3.6.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  http: ^1.2.2
  equatable: ^2.0.3
  google_fonts: ^6.2.1
  geolocator: ^13.0.2
  intl: ^0.20.1
  geocoding: ^3.0.0
  shared_preferences: ^2.0.15
  maths: any
  image_picker: ^1.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
 
